<?php

declare(strict_types=1);

namespace Fp4\PHP\Either;

use Closure;
use Fp4\PHP\Bindable;
use Fp4\PHP\PsalmIntegration\Module\Either\BindableCompressor;
use Fp4\PHP\PsalmIntegration\Module\Either\BindFunctionStorageProvider;
use Fp4\PHP\PsalmIntegration\Module\Either\LetFunctionStorageProvider;

/**
 * @return Either<never, Bindable>
 */
function bindable(): Either
{
    return right(new Bindable());
}

/**
 * Signature will be generated by {@see BindFunctionStorageProvider} plugin hook.
 * Return type will be post processed by {@see BindableCompressor} plugin hook.
 *
 * @param Closure(Bindable): Either ...$params
 * @return Closure(Either<mixed, Bindable>): Either<mixed, Bindable>
 */
function bind(Closure ...$params): Closure
{
    return function(Either $context) use ($params) {
        if (isLeft($context)) {
            return $context;
        }

        $bindable = $context->value;

        foreach ($params as $key => $param) {
            $result = $param($bindable);

            if (isLeft($result)) {
                return $result;
            }

            $bindable = $bindable->with((string) $key, $result->value);
        }

        return right($bindable);
    };
}

/**
 * Signature will be generated by {@see LetFunctionStorageProvider} plugin hook.
 * Return type will be post processed by {@see BindableCompressor} plugin hook.
 *
 * @param Closure(Bindable): mixed ...$params
 * @return Closure(Either<mixed, Bindable>): Either<mixed, Bindable>
 */
function let(Closure ...$params): Closure
{
    return function(Either $context) use ($params) {
        if (isLeft($context)) {
            return $context;
        }

        $bindable = $context->value;

        foreach ($params as $key => $param) {
            $bindable = $bindable->with((string) $key, $param($bindable));
        }

        return right($bindable);
    };
}
