<?php

declare(strict_types=1);

namespace Fp4\PHP\ArrayList;

use Closure;
use Fp4\PHP\Bindable;
use Fp4\PHP\PsalmIntegration\Module\ArrayList\BindableCompressor;
use Fp4\PHP\PsalmIntegration\Module\ArrayList\BindFunctionStorageProvider;
use Fp4\PHP\PsalmIntegration\Module\ArrayList\LetFunctionStorageProvider;

/**
 * @return list<Bindable>
 */
function bindable(): array
{
    return [new Bindable()];
}

/**
 * Signature will be generated by {@see BindFunctionStorageProvider} plugin hook.
 * Return type will be post processed by {@see BindableCompressor} plugin hook.
 *
 * @param Closure(Bindable): list<mixed> ...$params
 * @return Closure(list<Bindable>): list<Bindable>
 */
function bind(Closure ...$params): Closure
{
    return function(array $list) use ($params) {
        foreach ($params as $key => $param) {
            $cartesian = [];

            foreach ($list as $bindable) {
                foreach ($param($bindable) as $item) {
                    $cartesian[] = $bindable->with((string) $key, $item);
                }
            }

            $list = $cartesian;
        }

        return $list;
    };
}

/**
 * Signature will be generated by {@see LetFunctionStorageProvider} plugin hook.
 * Return type will be post processed by {@see BindableCompressor} plugin hook.
 *
 * @param Closure(Bindable): mixed ...$params
 * @return Closure(list<Bindable>): list<Bindable>
 */
function let(Closure ...$params): Closure
{
    return function(array $list) use ($params) {
        foreach ($params as $key => $param) {
            $cartesian = [];

            foreach ($list as $bindable) {
                $cartesian[] = $bindable->with((string) $key, $param($bindable));
            }

            $list = $cartesian;
        }

        return $list;
    };
}
