name: CI

on:
  pull_request: ~
  push:
    branches: [ '*' ]

jobs:
  composer-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.1 ]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - run: composer validate --strict --ansi

  composer-normalize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.1 ]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - run: composer normalize --dry-run --diff --ansi

  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.1 ]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - run: composer fixcs -- --dry-run --diff --format=checkstyle --ansi | cs2pr

  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.1, 8.2 ]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - run: composer psalm -- --php-version=${{ matrix.php }} --stats --output-format=github

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    #      - psalm
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Restore cached composer dependencies
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ github.sha }}

      - name: Run test suite
        run: php vendor/bin/phpunit

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php vendor/bin/coveralls.php --coverage_clover=build/logs/clover.xml -v